[workspace]
authors = ["Mike Smyth <Mike.M.Smyth@jpl.nasa.gov>"]
channels = ["conda-forge", "/home/smyth/Local/afids-conda-package/afids-conda-channel"]
name = "build-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure = "/ldata/smyth/vicar-gdalplugin/env//../configure --prefix=$CONDA_PREFIX"

[dependencies]
git = "*"
perl = "*"
patch = "*"
make = "*"
pkg-config = "*"
ncurses = "*"
libtool = "*"
automake = "*"
autoconf = "*"
vicar-rtl = "*"
libgdal = "*"
geotiff = "*"
boost = "*"
expat = "*"
gcc = ">=15.2.0,<15.3"
gxx = ">=15.2.0,<15.3"
gfortran = ">=15.2.0,<15.3"
